name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 every day, change as necessary
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for the pull request.

      - name: Sync fork
        uses: tgymnich/fork-sync@v1.9
        with:
          owner: apache
          repository: superset
          base: master
          head: master

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master