name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 every day, change as necessary
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for the pull request.

      - name: Fetch upstream changes
        run: git fetch upstream
      
      - name: Merge upstream changes into master
        run: git merge upstream/master
      
      - name: Push changes to fork
        run: git push origin master
