name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          owner: apache
          repo: superset
          base: master
          head: master
