name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 every day, change as necessary
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures all branches are fetched

    - name: Sync fork
      uses: tgymnich/fork-sync@v1.3
      with:
        owner: apache
        repository: superset
        base: master  # Adjust this if your base branch differs
        head: master  # Adjust this if your target branch differs

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master  # Adjust this if your target branch differs
