name: Sync Fork with Upstream
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC, adjust as needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch upstream changes
        run: git fetch upstream
      
      - name: Merge upstream changes into master
        run: git merge upstream/master
      
      - name: Push changes to fork
        run: git push origin master
